name: CI and CD
on:
  push:
  pull_request:
jobs:
  tf:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_API_TOKEN: ${{ secrets.TERRAFORM_CLOUD_API_TOKEN }}
      TF_VAR_discord_bot_token: ${{ secrets.DISCORD_BOT_TOKEN }}
      TF_IN_AUTOMATION: true
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ env.TF_API_TOKEN }}
      # - name: Terraform Fmt
      #   run: terraform fmt -check
      - name: Terraform Init
        run: terraform init
      # - name: Validate .tf files
      #   run: terraform validate
      # - name: Plan Terraform infrastructure changes
      #   run: terraform plan -input=false -no-color
      #   id: plan
      # - name: Comment plan result to Pull Request
      #   uses: robburger/terraform-pr-commenter@v1
      #   if: always() && github.ref != 'refs/heads/main' && (steps.plan.outcome == 'success' || steps.plan.outcome == 'failure')
      #   with:
      #     commenter_type: plan
      #     commenter_input: ${{ format('{0}{1}', steps.plan.outputs.stdout, steps.plan.outputs.stderr) }}
      #     commenter_exitcode: ${{ steps.plan.outputs.exitcode }}
      # - name: Terraform Apply
      #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      #   run: terraform apply -input=false -auto-approve
      - run: terraform destroy -input=false -auto-approve
